### ISSUE TITLE
Invalid JDK verison in profile

### ISSUE THREAD

**Issue by blommish** [dropwizard/dropwizard#1325]
Dropwizard 0.9.1
org.glassfish.jersey.core does exist on nexus
Reason: Invalid JDK version in profile 'javadoc-jdk8+': Unbounded range: [1.8 for project unknown:hk2-parent

Some names are changed, but the structure is the same

maven:

	Unable to get dependency information: Unable to read the metadata file for artif
	act 'org.glassfish.hk2:hk2-api:jar': Invalid JDK version in profile 'javadoc-jdk
	8+': Unbounded range: [1.8 for project unknown:hk2-parent
	  org.glassfish.hk2:hk2-api:jar:2.4.0-b31

	from the specified remote repositories:
	  central (http://repo1.maven.org/maven2),
	  abc-snapshots (http://:8081/nexus/content/repositories/snapshots),
	  sonatype-nexus-snapshots (http://oss.sonatype.org/content/repositories/snapsho
	ts)

	Path to dependency:
			1) .admin:rgadmin:jar:1.0.0-SNAPSHOT
			2) io.dropwizard:dropwizard-core:jar:0.9.1
			3) io.dropwizard:dropwizard-jersey:jar:0.9.1
			4) org.glassfish.jersey.core:jersey-server:jar:2.22.1
			5) org.glassfish.jersey.core:jersey-common:jar:2.22.1

code:

	<?xml version="1.0" encoding="UTF-8"?>
	<project xmlns="http://maven.apache.org/POM/4.0.0"
			 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	  <modelVersion>4.0.0</modelVersion>

	  <parent>
		<groupId>parent</groupId>
		<artifactId>parent</artifactId>
		<version>3.0.0</version>
	  </parent>

	  <groupId>com.abc.admin</groupId>
	  <artifactId>rgadmin</artifactId>
	  <version>1.0.0-SNAPSHOT</version>

	  <properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<dropwizard.version>0.9.1</dropwizard.version>
	  </properties>

	  <dependencies>
		<dependency>
		  <groupId>io.dropwizard</groupId>
		  <artifactId>dropwizard-core</artifactId>
		  <version>${dropwizard.version}</version>
		</dependency>
	  </dependencies>

	</project>

**Comment by joschi** [comment]
Which Java/JDK version are you using?

**Comment by joschi** [comment]
FWIW, a short Google search reveals https://java.net/jira/browse/JERSEY-2881 and https://java.net/jira/browse/HK2-277

**Comment by blommish** [comment]
Tried JDK 1.7/1.8
But it might be as simple as the jar does not exist on our nexus and it does not get downloaded.. 
I came to the conclusion after writing it here that the issue is not actually related to dropwizard at all..

**Comment by blommish** [comment]
Very weird, but putting my dependencies in dependencyManagement solved it..

**Comment by joschi** [comment]
The offending POM (hk2-parent) has been fixed between HK2 2.4.0-b31 and HK2 2.4.0-b32:

* https://github.com/hk2-project/hk2/blob/hk2-parent-2.4.0-b31/pom.xml#L1095-L1104
* https://github.com/hk2-project/hk2/blob/hk2-parent-2.4.0-b32/pom.xml#L1095-L1104
* https://github.com/hk2-project/hk2/commit/f9c846167b85d7a9a6915d522990b1ea6ca2b4ee

**Comment by blommish** [comment]
But that means I do need java 1.8. Shouldn't dropwizard work fine with 1.7?

**Comment by joschi** [comment]
@blommish No, that doesn't mean you need Java 8. It's just a profile that's being activated if Java 8 is being used. See http://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html for the reasons to have such a profile (which Dropwizard also has).

**Comment by blommish** [comment]
@joschi Hmm, I do not get this to work at all. If I understand ir correctly, the error should actually not happen when using Java 7. 
And running Java 8 with doclint turned off does not solve the problem
Reason: Invalid JDK version in profile 'javadoc-jdk8+': Unbounded range: [1.8 for project unknown:hk2-parent

**Comment by joschi** [comment]
@blommish The problem is that the Maven Enforcer plugin (rightfully) complains about the (invalid) version range in the hk2-parent 2.4.0-b31 POM. You can either deactivate this check, remove the Maven Enforcer plugin, or override the version of HK2 being used in your project (which will bring some problems with the Maven Enforcer plugin if you're using it).

**Comment by blommish** [comment]
@joschi I finally found it. Due to the parent pom we are using, we cannot have maven 3+, therefor using Maven 2.2.1. When running maven 3.3.3 it worked.

Thanks a lot for your help and explanations!
