### ISSUE TITLE
Caching Http Client

### ISSUE THREAD

**Issue by gurrie** [dropwizard/dropwizard#1633]
Hi All, 

I would like to implement the ability to create a caching http client (https://hc.apache.org/httpcomponents-client-ga/tutorial/html/caching.html) when using the JerseyClientBuilder. 

Is there any interest in this feature? Or is this ability already present and I am just missing something? 

The rationale for the request is that on my project we have a number of collaborating microservices, and it would be desirable to reduce the number of network requests that are made by specifying the appropriate HTTP cache headers on each response and having the clients cache the data for the specified period. I have previously posted to both the dev and user mailing lists but haven't received any responses.

Any feedback or suggestions would be greatly appreciated.

Kind Regards 
Brian

**Comment by arteam** [comment]
Hi, @gurrie. Sorry for the lack of feedback in the mailing lists, usually we try to answer to such questions.

I think your proposal is an interesting feature and I can see other users who can be interested in it. Dropwizard is quite often used in projects consisting of many microservices, so the benefits of client-side caching can be quite extensive. Considering we can provide an external cache configuration for the application administrators, it can be a powerful way to optimize existed Dropwizard application which make a lot of HTTP requests. 

But I am a little bit skeptic about including such functionality in the project's core. We will need to pull external library `httpclient-cache` and make caching transparent to the user. Despite it looks like that the Apache Client makes it rather easy (`CachingHttpClientBuilder` extends `HttpClientBuilder`), there could be some hidden issues. Also people tend to use complex caching solutions like EhCache, Memcached, Redis, Hazelcast, etc.., so naturally they would want to have them supported as in the core as well. I don't want to open a Pandora's box.

What do you think about starting to work on this feature as an external Dropwizard module? In the core we could expose some internals of `io.dropwizard.client.HttpClientBuilder` for overriding, if you want to reuse some of its functionality.

**Comment by gurrie** [comment]
Hi,

Many thanks for the feedback. My thinking was not to replace the existing http client with the caching client but rather to provide an option on the JerseyClientBuilder to create a caching client or a standard client. That way the developer would be free to chose the implementation based on their needs. 

As you mentioned this would require pulling in the httpclient-cache module as a dependancy. If you are still uncomfortable with putting it in the core, I would be happy to create it as an external module, but as you mentioned it would require a few changes to the existing code to support the change. 

I am happy to describe what I would require in that case if you see this as being beneficial? It would also potentially be beneficial to instrument the cache so we could provide metrics on the cache usage etc.

Regards
Brian

**Comment by gurrie** [comment]
Do you think it would be beneficial to move this conversation to the dev mailing list?

**Comment by evnm** [comment]
I think a mailing list thread would be a good recourse if we can't come to agreement here in a timely fashion, but I don't think it's necessary just yet. If developing a separate module is acceptable to you, I think we can move forward. Exposing certain internals of `HttpClientBuilder` strikes me as a reasonable idea, as there very well may be other use cases that could be neatly solved by extending it.

**Comment by gurrie** [comment]
Hey, nope if you guys would prefer it as a standalone module that's fine.
Would you like me to explain which changes would be required or do you have
an idea already?

**Comment by nickbabcock** [comment]
Closed by #1662, as it allows customizing the builder to add caching if desired.

**Comment by yq314** [comment]
https://github.com/dropwizard/dropwizard/pull/1668 doesn't seem to solve this problem, `customizeBuilder` accepts and returns a `HttpClientBuilder` but doesn't allow overriding it, so I'm still not able to use `CachingHttpClientBuilder` here.

**Comment by joschi** [comment]
@yq314 `HttpClientBuilderTest` shows how to override the `org.apache.http.impl.client.HttpClientBuilder` being used:

https://github.com/dropwizard/dropwizard/blob/2b968a68f24caba228ac0bede96ca9e000ae91f3/dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java#L85-L100
https://github.com/dropwizard/dropwizard/blob/2b968a68f24caba228ac0bede96ca9e000ae91f3/dropwizard-client/src/test/java/io/dropwizard/client/HttpClientBuilderTest.java#L712-L718

If that's not what you mean, please elaborate on your use case and what you've already tried to do.

**Comment by yq314** [comment]
Hi @joschi ,

Thanks for the reply. So this `customizeBuilder` doesn't allow me to do this to set `CacheConfig` because I can't call `setCacheConfig` on `org.apache.http.impl.client.HttpClientBuilder`:

```java
org.apache.http.impl.client.cache.CachingHttpClientBuilder builder = org.apache.http.impl.client.cache.CachingHttpClientBuilder.create();

        CacheConfig cacheConfig = CacheConfig.custom()
            .setMaxObjectSize(cacheConfiguration.getMaxObjectSize())
            .setMaxCacheEntries(cacheConfiguration.getMaxCacheEntries())
            .setMaxUpdateRetries(cacheConfiguration.getMaxUpdateRetries())
            .setAllow303Caching(cacheConfiguration.isAllow303Caching())
            .setWeakETagOnPutDeleteAllowed(cacheConfiguration.isWeakETagOnPutDeleteAllowed())
            .setHeuristicCachingEnabled(cacheConfiguration.isHeuristicCachingEnabled())
            .setHeuristicCoefficient(cacheConfiguration.getHeuristicCoefficient())
            .setHeuristicDefaultLifetime(cacheConfiguration.getHeuristicDefaultLifetime())
            .setSharedCache(cacheConfiguration.isSharedCache())
            .setAsynchronousWorkersMax(cacheConfiguration.getAsynchronousWorkersMax())
            .setAsynchronousWorkersCore(cacheConfiguration.getAsynchronousWorkersCore())
            .setAsynchronousWorkerIdleLifetimeSecs(cacheConfiguration.getAsynchronousWorkerIdleLifetimeSecs())
            .setRevalidationQueueSize(cacheConfiguration.getRevalidationQueueSize())
            .build();
        builder.setCacheConfig(cacheConfig);
```

What I'm doing now to workaround this is to override `buildWithDefaultRequestConfiguration`:

```java
public class CachingHttpClientBuilder extends HttpClientBuilder {
    private final CacheConfiguration cacheConfiguration;

    @Inject
    public CachingHttpClientBuilder(final Environment environment,
                                    final JerseyClientConfiguration jerseyClientConfiguration) {
        super(environment);
        super.using(jerseyClientConfiguration);
        this.cacheConfiguration = jerseyClientConfiguration.getCacheConfiguration();
    }

    @Override
    ConfiguredCloseableHttpClient buildWithDefaultRequestConfiguration(String name) {
        org.apache.http.impl.client.cache.CachingHttpClientBuilder builder = org.apache.http.impl.client.cache.CachingHttpClientBuilder.create();

        CacheConfig cacheConfig = CacheConfig.custom()
            .setMaxObjectSize(cacheConfiguration.getMaxObjectSize())
            .setMaxCacheEntries(cacheConfiguration.getMaxCacheEntries())
            .setMaxUpdateRetries(cacheConfiguration.getMaxUpdateRetries())
            .setAllow303Caching(cacheConfiguration.isAllow303Caching())
            .setWeakETagOnPutDeleteAllowed(cacheConfiguration.isWeakETagOnPutDeleteAllowed())
            .setHeuristicCachingEnabled(cacheConfiguration.isHeuristicCachingEnabled())
            .setHeuristicCoefficient(cacheConfiguration.getHeuristicCoefficient())
            .setHeuristicDefaultLifetime(cacheConfiguration.getHeuristicDefaultLifetime())
            .setSharedCache(cacheConfiguration.isSharedCache())
            .setAsynchronousWorkersMax(cacheConfiguration.getAsynchronousWorkersMax())
            .setAsynchronousWorkersCore(cacheConfiguration.getAsynchronousWorkersCore())
            .setAsynchronousWorkerIdleLifetimeSecs(cacheConfiguration.getAsynchronousWorkerIdleLifetimeSecs())
            .setRevalidationQueueSize(cacheConfiguration.getRevalidationQueueSize())
            .build();
        builder.setCacheConfig(cacheConfig);

        return createClient(builder, createConnectionManager(createConfiguredRegistry(), name), name);
    }
}
```

But since `buildWithDefaultRequestConfiguration` is package private, I had to put my `CachingHttpClientBuilder` under `io.dropwizard.client` package which is not very ideal.

Another problem I'm having is that https://github.com/dropwizard/dropwizard/blob/2b968a68f24caba228ac0bede96ca9e000ae91f3/dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java#L359 happens after calling `customizeBuilder()` so the customized request executor I set inside `customizeBuilder` will be overridden. I need to provide a custom request executor in order to inject some caching related metrics.

**Comment by joschi** [comment]
@yq314 You can modify the used `org.apache.http.impl.client.HttpClientBuilder` in your custom `HttpClientBuilder` sub-class by overriding the `customizeBuilder()` method.

**Comment by yq314** [comment]
Hi @joschi sorry if I didn't make it clear, let's me try to clarify the problem again:

There are 2 problems that `customizeBuilder` doesn't solve at the moment:

1. I need to pass a different builder to `createClient`, which is called in the package private method `buildWithDefaultRequestConfiguration`. If I'm overriding `buildWithDefaultRequestConfiguration` I don't actually need `customizeBuilder` as I can directly do customization when I create the builder in `buildWithDefaultRequestConfiguration`.

2. There are bunches of setter method called on the return value of `customizeBuilder` which will override whatever I customized in the builder, it will be nicer if those methods are called before https://github.com/dropwizard/dropwizard/blob/2b968a68f24caba228ac0bede96ca9e000ae91f3/dropwizard-client/src/main/java/io/dropwizard/client/HttpClientBuilder.java#L358

**Comment by yq314** [comment]
Created a PR to move call to `customizeBuilder` to the bottom of `createClient()` that should solve the above problem 2.
