### ISSUE TITLE
Liquibase dependency (3.5.3) doesn't work with Java 9

### ISSUE THREAD

**Issue by eodonohoe** [dropwizard/dropwizard#2163]
It appears to throw a StringOutOfBoundsException while parsing the new Java version.  Its expecting a 3 character version string (eg. '1.9') but it receives '9'.  

A pull request has been created here: https://github.com/liquibase/liquibase/pull/688

**Comment by nickbabcock** [comment]
Thank you for reporting this. I'll mark it as "blocked" so we know that it is an upstream issue.

I believe, other than dropwizard-migrations, everything else should work on Java 9. Quoting @mattnelson from an dev email chain (hope he doesn't mind :smile:)

> The only change related to dropwizard I had to make was to add "--add-modules java.xml.bind"

**Comment by arteam** [comment]
I think jadira also doesn't work with Java 9. I created a PR fix this: https://github.com/JadiraOrg/jadira/pull/66.

I created a [java_9_build](https://github.com/dropwizard/dropwizard/tree/java_9_build) branch where I'm trying to build Dropwizard under Java9. There's good progress, most of the basic functions work, but some modules are still not Java9 compatible.

**Comment by arteam** [comment]
The Java 9 branch has been merged to the upstream and the Liquibase tests pass. I presume the version check fails when one tries to run migration commands, right?

**Comment by eodonohoe** [comment]
Yes, that was the behaviour I encountered.

**Comment by nvoxland** [comment]
Merged into master. I also merged it into the 3.5.x release for the next patch release.

**Comment by ramsrib** [comment]
Is this issue fixed in the latest version (1.2.3 or 1.3.0-rc4)?

**Comment by joschi** [comment]
@ramsrib Please check out Dropwizard 1.3.0-rc5 and give us feedback, whether it solves your issue.

**Comment by ramsrib** [comment]
@joschi Tested with 1.3.0-rc5 (compiled against Java 9) and it worked perfectly.

**Comment by eodonohoe** [comment]
This is still broken for me with 1.3.0 running liquibase 3.5.5.  There is missing commit in that build but it is in the 3.6.0 branch

Caused by: java.lang.StringIndexOutOfBoundsException: begin 2, end 3, length 1
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3116)
	at java.base/java.lang.String.substring(String.java:1885)
	at liquibase.util.SystemUtils.getJavaVersionAsInt(SystemUtils.java:1184)

**Comment by avboy72** [comment]
It appears that this fix was temporary hack, as it is broken again in Java 10. Java 9 is now end of life.

**Comment by nickbabcock** [comment]
Closing this as Dropwizard v1.3.4 includes Liquibase 3.6.1, which should contain the missing commit. Respond back if this is still an issue.
