### ISSUE TITLE
dropwizard-parent:1.3.6 is missing in jCenter

### ISSUE THREAD

**Issue by seanstaley** [dropwizard/dropwizard#2513]
Looks like the latest Dropwizard release (1.3.6) wasn't fully deployed to jCenter:
https://jcenter.bintray.com/io/dropwizard/dropwizard-parent/

Looks like it does exist in Maven Central:
http://central.maven.org/maven2/io/dropwizard/dropwizard-parent/1.3.6/

**Comment by seanstaley** [comment]
Having the same issue today with 1.3.7 with dropwizard-core.

**Comment by isaki** [comment]
I can confirm, it isn't even listed:

https://repo.maven.apache.org/maven2/io/dropwizard/dropwizard-core/

**Comment by arteam** [comment]
Sigh, the Sonatype's OSS repo is really weird. I will redeploy it manually.

**Comment by arteam** [comment]
I've released all the missed modules for 1.3.7, they should be in Maven Central in an hour.

**Comment by isaki** [comment]
Looks good, thank you!

**Comment by isaki** [comment]
This still seems to be an issue.

`Failure to find io.dropwizard:dropwizard-assets:jar:1.3.7 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]`

**Comment by arteam** [comment]
Hm, okay. Looks like a caching issue, I'm pretty sure the actual jar was deployed.

**Comment by isaki** [comment]
It's been quite a few hours and it is still missing. Any ideas?
